# Generated by Django 4.2 on 2024-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='volume',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
